database:
  connectionString: "postgres://postgres:postgres@localhost:5432/release_notifier?sslMode=disable"
server:
  host: "0.0.0.0"
  port: "8080"
  grpcPort: "50051"
scanner:
  interval: "1m"
eventBus:
  url: "amqp://guest:guest@localhost:5672/"
  notificationExchange: "notifications"
  notificationQueue: "notification-worker"
  notificationDLQ: "notification-worker.dlq"
github:
  url: "https://api.github.com"
  apiToken: ""
  timeout: "10s"
