notifier:
  smtpHost: "localhost"
  smtpPort: "1025"
  fromEmail: "noreply@release-notifier.com"
  baseUrl: "http://localhost:8080"
eventBus:
  url: "amqp://guest:guest@localhost:5672/"
  notificationExchange: "notifications"
  notificationQueue: "notification-worker"
  notificationDLQ: "notification-worker.dlq"
