version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

excludeFiles:
  - "^.*_test\\.go$"

components:
  cmd: { in: cmd/** }
  support: { in: internal/config }
  core: { in: internal/notification }
  email-adapter: { in: internal/adapters/email }
  eventbus-adapter: { in: internal/adapters/eventbus/** }

vendors:
  shared-contract-events: { in: github.com/GenesisEducationKyiv/software-engineering-school-6-0-Oleg-amur/shared/contracts/events }

deps:
  cmd:
    mayDependOn:
      - support
      - core
      - email-adapter
      - eventbus-adapter
    anyVendorDeps: true

  support:
    anyVendorDeps: true

  core:
    canUse:
      - shared-contract-events

  email-adapter:
    mayDependOn:
      - email-adapter
    anyVendorDeps: true

  eventbus-adapter:
    anyVendorDeps: true
