global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: release-notifier
    metrics_path: /metrics
    static_configs:
      - targets:
          - release-notifier:8080
